services:
  web:
    image: nginx:stable
    container_name: growth-mindset-web
    volumes:
      - ./.docker/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    ports:
      - "80:80"
    restart: always
    depends_on:
      - db
      - php
  php:
    build: .docker/php
    container_name: growth-mindset-php
    restart: always
    depends_on:
      - db
    env_file:
      - ./.docker/conf/php/.env
    environment:
      PHP_IDE_CONFIG: "serverName=GrowthMindset"
    volumes:
      - ./.docker/conf/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./.docker/conf/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - .:/var/www/html
  db:
    image: mysql:latest
    container_name: growth-mindset-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - .:/app
      - growth_mindset_data:/var/lib/mysql
    env_file:
      - .env
volumes:
  growth_mindset_data: {}
